//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public int IdCalendar { get; set; }
        public int ClassId { get; set; }
        public string DayLesson { get; set; }
        public int FromLesson { get; set; }
        public int ToLesson { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
