<?xml version="1.0" encoding="utf-8"?><Database Name="WebSiteEnglishCenter_7" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-7QF55P0T\SQLEXPRESS;Initial Catalog=WebSiteEnglishCenter_7;Integrated Security=True" SettingsObjectName="PBL3.Properties.Settings" SettingsPropertyName="WebSiteEnglishCenter_7ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Role_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="Account_Account_Info" Member="Account_Info" ThisKey="ID" OtherKey="Account_ID" Type="Account_Info" Cardinality="One" />
      <Association Name="Account_Bill" Member="Bills" ThisKey="ID" OtherKey="Account_ID" Type="Bill" />
      <Association Name="Account_LearningResult" Member="LearningResults" ThisKey="ID" OtherKey="Account_ID" Type="LearningResult" />
      <Association Name="Role_Account" Member="Role" ThisKey="Role_ID" OtherKey="ID" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Account_Info" Member="Account_Infos">
    <Type Name="Account_Info">
      <Column Name="Account_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Account_Account_Info" Member="Account" ThisKey="Account_ID" OtherKey="ID" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bill" Member="Bills">
    <Type Name="Bill">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Account_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Account_Bill" Member="Account" ThisKey="Account_ID" OtherKey="ID" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Class" Member="Classes">
    <Type Name="Class">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Course_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MaxStudent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Class_Document" Member="Documents" ThisKey="ID" OtherKey="Class_ID" Type="Document" />
      <Association Name="Class_LearningResult" Member="LearningResults" ThisKey="ID" OtherKey="Class_ID" Type="LearningResult" />
      <Association Name="Course_Class" Member="Course" ThisKey="Course_ID" OtherKey="ID" Type="Course" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Course" Member="Courses">
    <Type Name="Course">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Start_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="End_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Course_Class" Member="Classes" ThisKey="ID" OtherKey="Course_ID" Type="Class" />
    </Type>
  </Table>
  <Table Name="dbo.Document" Member="Documents">
    <Type Name="Document">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Class_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Association Name="Class_Document" Member="Class" ThisKey="Class_ID" OtherKey="ID" Type="Class" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LearningResult" Member="LearningResults">
    <Type Name="LearningResult">
      <Column Name="Account_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Class_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Assignment_Point" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MidTermExam_Point" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FinalExam_Point" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Account_LearningResult" Member="Account" ThisKey="Account_ID" OtherKey="ID" Type="Account" IsForeignKey="true" />
      <Association Name="Class_LearningResult" Member="Class" ThisKey="Class_ID" OtherKey="ID" Type="Class" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Role_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Role_Account" Member="Accounts" ThisKey="ID" OtherKey="Role_ID" Type="Account" />
    </Type>
  </Table>
</Database>