//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LearningResult()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public int Id { get; set; }
        public int AccountId { get; set; }
        public int ClassId { get; set; }
        public Nullable<double> AssignmentPoint { get; set; }
        public Nullable<double> MidTermExamPoint { get; set; }
        public Nullable<double> FinalExamPoint { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual Class Class { get; set; }
    }
}
