//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningResult
    {
        public int Account_ID { get; set; }
        public int Class_ID { get; set; }
        public Nullable<double> Assignment_Point { get; set; }
        public Nullable<double> MidTermExam_Point { get; set; }
        public Nullable<double> FinalExam_Point { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Class Class { get; set; }
    }
}
